---
demographics:
  min_age: 18
  max_age: 150
  required_properties:
  - opticcolor
  - basecolor
  - trimcolor
  - fullname
  - gender
  nickname_field: callsign
  nickname_format: "%{name} (%{nickname})"
  disable_auto_shortcuts: false
  editable_properties:
  - fullname
  - gender
  - opticcolor
  - basecolor
  - trimcolor
  demographics:
  - fullname
  - gender
  - opticcolor
  - basecolor
  - trimcolor
  groups:
    League:
      desc: Leagues encompassing all major sports with various teams.
      values:
        Silver Flag League: Test
        Dark Sports Foundation: Test
    Class:
      desc: >-
      The family of sport of which your Leaguer belongs. See wiki for more details.
      values:
        Target Class: 'Bowling, golf (+3 Aiming)'
        Haven Class: 'Baseball, cricket (+3 Aiming)'
        Striking Class: 'Karate, boxing (+3 Melee)'
        Sword Class: 'Kendo, fencing, jousting (+3 Melee)'
        Goal Class: 'Soccer, hockey, football, basketball, rugby, roller derby (+3 Agility)'
        Volley Class: 'Tennis, volleyball (+3 Agility)'
    Model:
      desc: >-
      The model of your Leaguer, usually built to mimic traditional uniforms of a 
      specific sport. Only the listed models below are permitted.
      values:
        Soccer Leaguer: Test
        Baseball Leaguer: Test
        Hockey Leaguer: Test
        Football Leaguer: Test
        Basketball Leaguer: Test
        Volleyball Leaguer: Test
        Tennis Leaguer: Test
        Karate Leaguer: Test
        Kendo Leaguer: Test
        Boxing Leaguer: Test
        Bowling Leaguer: Test
        Golf Leaguer: Test
        Fencing Leaguer: Test
        Rugby Leaguer: Test
        Cricket Leaguer: Test
  shortcuts:
    groups: group
    colonies: group colony
    demographics: demographic
    birthday: birthdate
  help_text:
    gender: '%xcgender <male/female/other>%xn'
    opticcolor: '%xcopticcolor <eye color>%xn'
    basecolor: '%xcbasecolor <the color of the majority of your armor>%xn'
    trimcolor: '%xcbasecolor <the color of the trim on your armor>%xn'
  census_fields:
  - field: name
    width: 28
    title: Name
  - field: demographic
    width: 10
    title: Gender
    value: gender
  - field: group
    width: 10
    title: Model
    value: Model
  - field: group
    width: 10
    title: League
    value: League
  - field: group
    width: 20
    title: Rank
    value: Rank
  private_properties: []
